Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2023-11, with the labels that each got.

#246 Update OWNERS to add reviewer
  OWNERS
Labels: verified, can-be-merged, approved-rnetser

#250 Update pre-commit with ruff
  .flake8
  .pre-commit-config.yaml
  ocp_addons_operators_cli/cli.py
  ocp_addons_operators_cli/utils/addons_utils.py
  ocp_addons_operators_cli/utils/cli_utils.py
  ocp_addons_operators_cli/utils/general.py
  ocp_addons_operators_cli/utils/operators_utils.py
  pyproject.toml
Labels: verified, branch-main, size/L, can-be-merged, approved-rnetser

#253 flake8-plugins pin to version
  .flake8
  .pre-commit-config.yaml
Labels: verified, size/XS, branch-main, can-be-merged, approved-rnetser

#256 Remove redundant f-string formatting
  ocp_addons_operators_cli/utils/addons_utils.py
  ocp_addons_operators_cli/utils/cli_utils.py
  ocp_addons_operators_cli/utils/operators_utils.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove, approved-omrirh, approved-oharan2

#261 Add an option to run with `pdb`
  ocp_addons_operators_cli/cli.py
Labels: verified, branch-main, size/S, can-be-merged, approved-myakove

#259 Add source-image param for operator install
  README.md
  ocp_addons_operators_cli/cli.py
  ocp_addons_operators_cli/manifests/addons-operators.yaml.example
  ocp_addons_operators_cli/utils/operators_utils.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-rnetser
