Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2023-09, with the labels that each got.

#212 Update poetry
  poetry.lock
Labels: verified, branch-main, size/M, can-be-merged, ApprovedBy-rnetser

#216 update poetry to include updated redhat-qe-cloud-tools
  poetry.lock
Labels: verified, branch-main, size/L

#226 add chetna14manku in owner file
  OWNERS
Labels: size/XS, branch-main, ApprovedBy-rnetser
