Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2023-06, with the labels that each got.

#101 Edit OWNERS file
  OWNERS
Labels: verified, size/XS, branch-main, Approved-by-myakove, can-be-merged

#99 dockerfile set python version to 3.11
  Dockerfile
Labels: verified, size/XS, branch-main

#104 Support multiple uses of --rosa
  README.md
  app/addon_cmds/commands.py
Labels: verified, Approved-by-rnetser, branch-main, Approved-by-myakove, size/S, can-be-merged

#108 Update rosa-python-client: version 1.0.8
  poetry.lock
Labels: verified, size/XS, branch-main, Approved-by-myakove, can-be-merged

#107 Use rosa flag as a single line and parse mutliple value
  README.md
  app/addon_cmds/commands.py
Labels: verified, Approved-by-rnetser, branch-main, Approved-by-myakove, size/M, can-be-merged

#111 Extract set os debug to function
  app/addon_cmds/commands.py
  app/operator_cmds/commands.py
  app/utils.py
Labels: verified, Approved-by-rnetser, size/XS, branch-main, can-be-merged

#123 Update rosa-python-client to v1.0.10
  poetry.lock
Labels: verified, size/XS, branch-main, Approved-by-myakove, can-be-merged

#115 Refactor click
  README.md
  app/addon_cmds/commands.py
  app/cli.py
  app/click_dict_type.py
  app/operator_cmds/commands.py
  app/utils.py
Labels: verified, branch-main, size/XL

#125 Updating OWNERS
  OWNERS
Labels: size/XS, branch-main

#132 Set iib from json if env vars are set
  app/operator_cmds/commands.py
  app/utils.py
Labels: verified, branch-main, Approved-by-myakove, size/M, can-be-merged

#134 Update rosa-python-client to v1.0.14 and redhat-qe-cloud-tools to v1.0.7
  poetry.lock
Labels: verified, size/XS, branch-main, Approved-by-myakove, can-be-merged

#136 Rename JOB_NAME to INSTALL_FROM_IIB
  app/operator_cmds/commands.py
Labels: verified, size/XS, branch-main, Approved-by-myakove, can-be-merged
