Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2023-07, with the labels that each got.

#140 Poetry set versions
  poetry.lock
  pyproject.toml
Labels: verified, size/XXL, Approved-by-rnetser, branch-main, can-be-merged

#148 Update rosa-python-client to v1.0.21
  poetry.lock
Labels: verified, branch-main, Approved-by-myakove, size/S, can-be-merged

#157 update poetry
  poetry.lock
Labels: verified, Approved-by-rnetser, branch-main, can-be-merged, size/XL
