Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2023-05, with the labels that each got.

#11 Operator ns
  app/operator_cmds/commands.py
  poetry.lock
Labels: verified, Approved-by-myakove

#14 Getting brew pull-secret for RHODS
  app/addon_cmds/commands.py
Labels: verified, Approved-by-rnetser, branch-main, Approved-by-myakove, size/S

#18 Add support to install/uninstall addon with ROSA cli
  app/addon_cmds/commands.py
Labels: verified, Approved-by-rnetser, size/XS, branch-main, Approved-by-myakove

#21 run_action - use kwargs instead of args
  app/addon_cmds/commands.py
  poetry.lock
Labels: verified, size/XXL, branch-main, Approved-by-myakove

#23 default values for brew_token and api_host args - run_action
  app/addon_cmds/commands.py
Labels: verified, Approved-by-rnetser, size/XS, branch-main

#29 Operators - support multi-operators install/uninstall
  README.md
  app/addon_cmds/commands.py
  app/operator_cmds/commands.py
  app/utils.py
Labels: verified, branch-main, Approved-by-myakove, size/L

#37 dockerfile fix
  Dockerfile
Labels: verified, size/XS, branch-main

#39 Update poetry.lock
  poetry.lock
Labels: verified, size/XXL, branch-main

#43 test pr
  a
Labels: size/XS, branch-main

#45 Add makefile
  Makefile
Labels: verified, size/XS, branch-main

#50 Revert "Revert "Revert "test pr"""
  a
Labels: size/XS, branch-main

#54 Revert "Revert "Revert "Revert "Revert "test pr"""""
  a
Labels: size/XS, branch-main

#58 Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr"""""""
  a
Labels: size/XS, branch-main

#62 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr"""""""""
  a
Labels: size/XS, branch-main

#64 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr""""""""""
  a
Labels: size/XS, branch-main

#68 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr""""""""""""
  a
Labels: size/XS, branch-main

#70 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr"""""""""""""
  a
Labels: size/XS, branch-main

#72 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr""""""""""""""
  a
Labels: size/XS, branch-main

#74 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr"""""""""""""""
  a
Labels: size/XS, branch-main

#76 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr""""""""""""""""
  a
Labels: size/XS, branch-main

#78 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test pr"""""""""""""""""
  a
Labels: size/XS, branch-main

#84 Get iib for operator install
  app/operator_cmds/commands.py
Labels: verified, Approved-by-rnetser, size/XS, branch-main

#83 Require poetry to use version higher than 1.0.21 for openshift-cluster-management-python-wrapper
  poetry.lock
  pyproject.toml
Labels: verified, Approved-by-rnetser, size/XS, can-be-merged
