Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2024-01, with the labels that each got.

#379 Update poetry openshift-python-wrapper
  poetry.lock
  pyproject.toml
Labels: size/XXL, branch-main

#389 Update build command script
  ocp_addons_operators_cli/scripts/ocp-addons-operators-cli-build-command.py
Labels: verified, branch-main, size/S, can-be-merged, approved-myakove

#394 Add kubeconfig to command build
  ocp_addons_operators_cli/scripts/ocp-addons-operators-cli-build-command.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove
