Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2024-04, with the labels that each got.

#501 Get ocp version from cluster
  .flake8
  ocp_addons_operators_cli/cli.py
  ocp_addons_operators_cli/tests/__init__.py
  ocp_addons_operators_cli/tests/test_operators.py
  ocp_addons_operators_cli/utils/general.py
  ocp_addons_operators_cli/utils/operators_utils.py
  poetry.lock
  pyproject.toml
  pytest.ini
  tox.ini
Labels: verified, size/XXL, branch-main, can-be-merged, approved-myakove

#503 add operator name in iib log
  ocp_addons_operators_cli/utils/general.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-myakove

#507 Update readme
  README.md
  ocp_addons_operators_cli/cli.py
Labels: verified, branch-main, size/S, can-be-merged, approved-rnetser
