Repository RedHatQE/ocp-addons-operators-cli, pull requests merged in 2024-08, with the labels that each got.

#560 Fix cluster_name for must-gather dest-dir option
  ocp_addons_operators_cli/utils/operators_utils.py
Labels: verified, size/XS, branch-main, can-be-merged, approved-rnetser

#564 Require openshift-python-utilities v5.0.61 or above
  poetry.lock
  pyproject.toml
Labels: verified, size/XXL, branch-main, can-be-merged, approved-myakove

#567 Update required openshift-python-utilities version to 5.0.62
  poetry.lock
  pyproject.toml
Labels: verified, branch-main, can-be-merged, size/XL, approved-rnetser
